#!/usr/bin/env bash

cp env/project.properties account/src/main/resources
cp env/project.properties article/src/main/resources

echo "++ recompile projects ++"
./gradlew account:jar --daemon && ./gradlew article:jar --daemon

rsync -azP \
--include=account/build/libs/ \
--include=article/build/libs/ \
--include=env/ \
--exclude=.git \
--exclude-from="$(git -C . ls-files --exclude-standard -oi --directory > /tmp/excludes; echo /tmp/excludes)" \
. root@kotlin-cn.org:Kotlin-CN