#!/usr/bin/env bash

if [ '-b' = $1 ]; then
    echo '++ reload process with compile ++'
    cp project.properties account/src/main/resources && cp project.properties article/src/main/resources
    ./gradlew account:jar --daemon && ./gradlew article:jar --daemon
fi

echo '++ service stop ++'
pkill -f *article* && pkill -f *account*

#如果文件夹不存在，创建文件夹
if [ ! -d "log" ]; then
  mkdir log
fi

nohup java -jar account/build/libs/account-1.0.0-release.jar 9000 8081 > log/account.log &
nohup java -jar article/build/libs/article-1.0.0-release.jar 9001 8083 > log/article.log &
echo '++ service restart ++'