#!/usr/bin/env bash

echo '++ service stop ++'
pkill -f article && pkill -f account

#如果文件夹不存在，创建文件夹
if [ ! -d "/root/log" ]; then
  mkdir /root/log
fi

echo '++ service restart ++'

nohup java -jar /root/Kotlin-CN/account/build/libs/account-1.0.0-release.jar    9000 8080  > /root/log/account.log &
nohup java -jar /root/Kotlin-CN/article/build/libs/article-1.0.0-release.jar    9003 8083  > /root/log/article.log &
nohup java -jar /root/Kotlin-CN/misc/build/libs/misc-1.0.0-release.jar               8086  > /root/log/misc.log &