#!/usr/bin/env bash

echo '++ service stop ++'
pkill -f article && pkill -f account

#如果文件夹不存在，创建文件夹
if [ ! -d "/root/log" ]; then
  mkdir /root/log
fi

echo '++ service restart ++'

nohup java -jar /root/Kotlin-CN/account/build/libs/account-1.0.0-release.jar 9000 8080 > /root/log/account1.log &
#nohup java -jar /root/Kotlin-CN/account/build/libs/account-1.0.0-release.jar 9001 8081 > /root/log/account2.log &
#nohup java -jar /root/Kotlin-CN/account/build/libs/account-1.0.0-release.jar 9002 8082 > /root/log/account3.log &
nohup java -jar /root/Kotlin-CN/article/build/libs/article-1.0.0-release.jar 9003 8083 > /root/log/article1.log &
#nohup java -jar /root/Kotlin-CN/article/build/libs/article-1.0.0-release.jar 9004 8084 > /root/log/article2.log &
#nohup java -jar /root/Kotlin-CN/article/build/libs/article-1.0.0-release.jar 9005 8085 > /root/log/article3.log &