#!/usr/bin/env bash

mode=$1

if [ 'release' = ${mode} ]; then

  cp src/assets/js/Config.js /tmp/Config.js
  cp ../env/Config.js src/assets/js/Config.js
  cnpm install && npm run build
  cp /tmp/Config.js src/assets/js/Config.js

  rsync -azP dist/ root@106.75.105.42:frontend/

elif [ 'dev' = ${mode} ]; then

  cnpm install && npm run build
  rsync -azP dist/ root@debug.kotlin-cn.org:frontend/

else

  echo 'Error: deploy mode should be one of `release` or `dev`'
  echo 'try `./deploy dev` or `./deploy release` instead'
  exit -1

fi
