#!/usr/bin/env bash

cp src/assets/js/Config.js /tmp/Config.js
cp ../env/Config.js src/assets/js/Config.js
npm run build
cp /tmp/Config.js src/assets/js/Config.js

rsync -azP \
dist root@kotlin-cn.org:Kotlin-CN/forum_ui

